---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn global add vsce
      - make
  - name: publish_github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - '*.vsix'
      checksum:
        - sha512
    when:
      event: tag
